# ex: set ro:
# DO NOT EDIT.
# generated by smc (http://smc.sourceforge.net/)
# from file : AppClass.sm

import statemap


class AppClassState(statemap.State):

    def Entry(self, fsm):
        pass

    def Exit(self, fsm):
        pass

    def Digit(self, fsm):
        self.Default(fsm)

    def Dollar(self, fsm):
        self.Default(fsm)

    def EOS(self, fsm):
        self.Default(fsm)

    def Endl(self, fsm):
        self.Default(fsm)

    def Liter(self, fsm):
        self.Default(fsm)

    def Slash(self, fsm):
        self.Default(fsm)

    def Start(self, fsm):
        self.Default(fsm)

    def Unknown(self, fsm):
        self.Default(fsm)

    def UpperLiter(self, fsm):
        self.Default(fsm)

    def Default(self, fsm):
        msg = "\n\tState: %s\n\tTransition: %s" % (
            fsm.getState().getName(), fsm.getTransition())
        raise statemap.TransitionUndefinedException(msg)

class Map1_Default(AppClassState):

    def Start(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.ClearSMC()
        finally:
            fsm.setState(Map1.Start)
            fsm.getState().Entry(fsm)


    def UpperLiter(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Liter(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Digit(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Dollar(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Slash(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Endl(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Unknown(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


class Map1_Start(Map1_Default):

    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Slash(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isCounterNotZero()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterZero()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Server)
                fsm.getState().Entry(fsm)
        else:
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Start)
                fsm.getState().Entry(fsm)


class Map1_Server(Map1_Default):

    def Digit(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidServer() and ctxt.isCounterNotZero()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Server)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Digit(self, fsm)
        
    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Slash(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidServer() and ctxt.isValidString() and ctxt.isCounterNotZero()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterZero()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Resource)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Slash(self, fsm)
        
    def UpperLiter(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidServer()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Server)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.UpperLiter(self, fsm)
        
class Map1_Resource(Map1_Default):

    def Digit(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString() and ctxt.isCounterNotZero()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Resource)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Digit(self, fsm)
        
    def Dollar(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString() and ctxt.isCounterNotZero()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.DollarEnding)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Dollar(self, fsm)
        
    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Liter(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Resource)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Liter(self, fsm)
        
    def Slash(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString() and ctxt.isCounterNotZero()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterZero()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Path)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Slash(self, fsm)
        
    def UpperLiter(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Resource)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.UpperLiter(self, fsm)
        
class Map1_DollarEnding(Map1_Default):

    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Slash(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterZero()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Path)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Slash(self, fsm)
        
class Map1_Path(Map1_Default):

    def Digit(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString() and ctxt.isCounterNotZero()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Path)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Digit(self, fsm)
        
    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Acceptable()
        finally:
            fsm.setState(Map1.OK)
            fsm.getState().Entry(fsm)


    def Endl(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Acceptable()
        finally:
            fsm.setState(Map1.OK)
            fsm.getState().Entry(fsm)


    def Liter(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Path)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Liter(self, fsm)
        
    def Slash(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidString() and ctxt.isCounterNotZero() :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterZero()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Path)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Slash(self, fsm)
        
    def UpperLiter(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName() and ctxt.isValidString()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
                ctxt.LengthInc()
            finally:
                fsm.setState(Map1.Path)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.UpperLiter(self, fsm)
        
class Map1_OK(Map1_Default):
    pass

class Map1_Error(Map1_Default):

    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        endState = fsm.getState()
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(endState)


class Map1(object):

    Start = Map1_Start('Map1.Start', 0)
    Server = Map1_Server('Map1.Server', 1)
    Resource = Map1_Resource('Map1.Resource', 2)
    DollarEnding = Map1_DollarEnding('Map1.DollarEnding', 3)
    Path = Map1_Path('Map1.Path', 4)
    OK = Map1_OK('Map1.OK', 5)
    Error = Map1_Error('Map1.Error', 6)
    Default = Map1_Default('Map1.Default', -1)

class AppClass_sm(statemap.FSMContext):

    def __init__(self, owner):
        statemap.FSMContext.__init__(self, Map1.Start)
        self._owner = owner

    def __getattr__(self, attrib):
        def trans_sm(*arglist):
            self._transition = attrib
            getattr(self.getState(), attrib)(self, *arglist)
            self._transition = None
        return trans_sm

    def enterStartState(self):
        self._state.Entry(self)

    def getOwner(self):
        return self._owner

# Local variables:
#  buffer-read-only: t
# End:
